title: "Just a Blog to write about what I do"
author: "Raksha Mangasuli"
description: "Blog to pen down my thoughts about Tech, hobbies and more"
baseurl: "/blog"         
url: "https://raksha-mangasuli.github.io" 

permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: false                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", sidebaricon: home}
  - {title: "General", url: "/general/", icon: globe}
  - {title: "Tech", url: "/tech/", icon: laptop}
  - {title: "Hobbies", url: "/hobbies/", icon: heart}
  - {title: "Template", url: "/template/", icon: file}
  

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Subscribe, icon: rss, url: "#"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
 - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

include: ["_pages"]

sass:
  quiet_deps: true
  silence_deprecations: ['import', 'global-builtin', 'slash-div']

